language: node_js
node_js:
  - '4.6'
before_script:
  - npm install -g gulp
script:
  - echo 'Installing...' && echo -en 'travis_fold:start:install\\r'
  - node node_modules/@microsoft/rush/lib/rush.js install
  - echo -en 'travis_fold:end:install\\r'
  - echo 'Linking...' && echo -en 'travis_fold:start:link\\r'
  - node node_modules/@microsoft/rush/lib/rush.js link
  - echo -en 'travis_fold:end:link\\r'
  - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
  - node node_modules/@microsoft/rush/lib/rush.js rebuild
  - echo -en 'travis_fold:end:build\\r'

